'use client'

import { useMemo } from 'react'
import { useRouter } from 'next/navigation'
import {
  Command,
  CommandDialog,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
} from '@/components/ui/command'
import { useRole } from '@/lib/auth/useRole'
import navEntries from '@/lib/generated-nav.json'

// Pure page-jump search -- fuzzy-matches against the nav map (regenerated by
// `npm run bible:generate` from sidebar.tsx's own menuGroups, so it never
// drifts from the real sidebar) and respects the same page-access rule
// sidebar.tsx's own canSee() uses. No server round trip: the whole list is a
// few dozen entries, already bundled.
export default function NavSearchPalette({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const router = useRouter()
  const { isOwner, hasPageAccess } = useRole()

  const items = useMemo(
    () =>
      (navEntries as { label: string; route: string; pageKey?: string; ownerOnly?: boolean }[]).filter(
        (item) => (isOwner || !item.ownerOnly) && (isOwner || !item.pageKey || hasPageAccess(item.pageKey))
      ),
    [isOwner, hasPageAccess]
  )

  const go = (route: string) => {
    router.push(route)
    onOpenChange(false)
  }

  return (
    <CommandDialog open={open} onOpenChange={onOpenChange} title="Search" description="Jump to any page you can access.">
      <Command>
        <CommandInput placeholder="Search pages..." />
        <CommandList>
          <CommandEmpty>No matching page.</CommandEmpty>
          <CommandGroup>
            {items.map((item) => (
              <CommandItem key={item.route} value={item.label} onSelect={() => go(item.route)}>
                {item.label}
              </CommandItem>
            ))}
          </CommandGroup>
        </CommandList>
      </Command>
    </CommandDialog>
  )
}
