import type { Metadata } from "next";
import { Lato, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';
import ThemeProvider from '@/components/ThemeProvider';
import { RoleProvider } from '@/lib/auth/useRole';

// Runs before hydration so the theme is correct on first paint -- ThemeProvider's
// own React state sync (localStorage -> data-theme attribute) would otherwise
// flash the default theme for a frame on every load.
const THEME_INIT_SCRIPT = `
try {
  var t = localStorage.getItem('db-erp-theme');
  if (t && t !== 'slate') document.documentElement.setAttribute('data-theme', t);
} catch (e) {}
`;

// Lato -- clean, humanist sans (the Zoho-style look the user asked for), swapped
// in for Geist Sans. Not a variable font on Google Fonts, so weights are listed
// explicitly to cover the app's existing font-medium/font-semibold/font-bold usage.
// tokens.css's `--font-sans` reads this variable.
const bodyFont = Lato({
  variable: "--font-body",
  subsets: ["latin"],
  // Lato only ships 100/300/400/700/900 -- font-medium (500) falls back to the
  // browser's nearest match (400) rather than a font-weight that doesn't exist.
  weight: ["400", "700", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bodyFont.variable} ${geistMono.variable} h-full antialiased`}>
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
      </head>
      <body className="min-h-full flex flex-col">
        <RoleProvider>
          <ThemeProvider>
            {children}
            <Toaster position="top-right" />
          </ThemeProvider>
        </RoleProvider>
      </body>
    </html>
  );
}