#!/usr/bin/env tsx
// Rebuilds docs/bible/generated/*.md from live truth (the database + the route/nav
// source files) -- never hand-edited. Deterministic and idempotent: running it twice
// with nothing changed produces an identical byte-for-byte diff, which is what
// `npm run bible:check` and the pre-push hook rely on.
//
// Usage: npx tsx scripts/bible/generate.ts
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, relative } from 'node:path'
import { globSync } from 'glob'
import { supabaseAdmin } from './lib/supabase-admin'

const ROOT = resolve(__dirname, '../..')
const OUT_DIR = resolve(ROOT, 'docs/bible/generated')
const ERP_APP = resolve(ROOT, 'apps/erp/app')
const ERP_LIB = resolve(ROOT, 'apps/erp')

mkdirSync(OUT_DIR, { recursive: true })

const HEADER = (title: string) =>
  `<!-- AUTO-GENERATED by scripts/bible/generate.ts -- do not hand-edit. Run \`npm run bible:generate\`. -->\n# ${title}\n\n`

function write(file: string, content: string) {
  writeFileSync(resolve(OUT_DIR, file), content, 'utf8')
  console.log(`  wrote generated/${file}`)
}

// ---------------------------------------------------------------------------
// 1) schema.md -- tables, columns, types, FKs, comments, row estimates
// ---------------------------------------------------------------------------
async function genSchema() {
  const { data, error } = await supabaseAdmin.rpc('bible_introspect_schema')
  if (error) throw new Error(`bible_introspect_schema: ${error.message}`)
  type Row = {
    table_name: string; table_comment: string | null; column_name: string
    ordinal_position: number; data_type: string; is_nullable: boolean
    column_default: string | null; column_comment: string | null
    is_primary_key: boolean; foreign_table: string | null; foreign_column: string | null
    row_estimate: number
  }
  const rows = (data || []) as Row[]
  const byTable = new Map<string, Row[]>()
  for (const r of rows) {
    if (!byTable.has(r.table_name)) byTable.set(r.table_name, [])
    byTable.get(r.table_name)!.push(r)
  }

  let out = HEADER('Database Schema')
  out += `Live schema snapshot -- ${byTable.size} tables. Regenerate with \`npm run bible:generate\`.\n\n`
  const tableNames = [...byTable.keys()].sort()
  out += `## Tables\n\n`
  for (const t of tableNames) out += `- [${t}](#${t.replace(/_/g, '')})\n`
  out += '\n'

  for (const t of tableNames) {
    const cols = byTable.get(t)!.sort((a, b) => a.ordinal_position - b.ordinal_position)
    const estimate = Math.max(0, Math.round(cols[0]?.row_estimate ?? 0))
    out += `## ${t}\n\n`
    if (cols[0]?.table_comment) out += `${cols[0].table_comment}\n\n`
    out += `~${estimate.toLocaleString('en-IN')} rows (estimate)\n\n`
    out += `| Column | Type | Null? | Default | Key | Comment |\n|---|---|---|---|---|---|\n`
    for (const c of cols) {
      const key = c.is_primary_key ? 'PK' : c.foreign_table ? `FK -> ${c.foreign_table}.${c.foreign_column}` : ''
      out += `| ${c.column_name} | ${c.data_type} | ${c.is_nullable ? 'yes' : 'no'} | ${c.column_default ? '`' + c.column_default.replace(/\|/g, '\\|') + '`' : ''} | ${key} | ${c.column_comment ?? ''} |\n`
    }
    out += '\n'
  }
  write('schema.md', out)
}

// ---------------------------------------------------------------------------
// 2) api-routes.md -- every app/api/**/route.ts: methods, auth helper, role gate
// ---------------------------------------------------------------------------
function genApiRoutes() {
  const files = globSync('api/**/route.ts', { cwd: ERP_APP }).sort()
  let out = HEADER('API Routes')
  out += `${files.length} route files under \`apps/erp/app/api/\`.\n\n`
  out += `| Route | Methods | Auth | Notable guards |\n|---|---|---|---|\n`

  for (const f of files) {
    const abs = resolve(ERP_APP, f)
    const src = readFileSync(abs, 'utf8')
    const methods = [...src.matchAll(/export\s+async\s+function\s+(GET|POST|PUT|PATCH|DELETE)\s*\(/g)]
      .map((m) => m[1])
    const route = '/' + f.replace(/\/route\.ts$/, '')
    const usesSession = /getSessionUser|getCookieSessionUser/.test(src)
    const guards: string[] = []
    if (/isOwner\(/.test(src)) guards.push('owner-only')
    if (/isManagerOrAbove\(/.test(src)) guards.push('manager+')
    if (/hasPageAccess\(/.test(src)) guards.push('page-access')
    if (/canEditPage\(/.test(src)) guards.push('edit-grant')
    if (/redactForRole|redactManyForRole/.test(src)) guards.push('redacted')
    if (/supabaseAdmin/.test(src)) guards.push('service-role')
    const auth = usesSession ? 'session' : /getSessionUser/.test(src) ? 'session' : 'none found'
    out += `| \`${route}\` | ${methods.join(', ') || '?'} | ${auth} | ${guards.join(', ') || '—'} |\n`
  }
  write('api-routes.md', out)
}

// ---------------------------------------------------------------------------
// 3) nav-map.md -- parse components/sidebar.tsx's menuGroups literal
// ---------------------------------------------------------------------------
interface NavItem { label: string; href?: string; pageKey?: string; ownerOnly?: boolean; children?: NavItem[] }

function genNavMap() {
  const src = readFileSync(resolve(ERP_LIB, 'components/sidebar.tsx'), 'utf8')
  const start = src.indexOf('const menuGroups = [')
  const arrStart = src.indexOf('[', start)
  // Bracket-match to find the end of the menuGroups array literal.
  let depth = 0, i = arrStart, end = -1
  for (; i < src.length; i++) {
    if (src[i] === '[') depth++
    else if (src[i] === ']') { depth--; if (depth === 0) { end = i; break } }
  }
  const literal = src.slice(arrStart, end + 1)

  // The literal is TS object syntax (unquoted keys, JSX icon refs) -- not valid JSON.
  // Extract group/child blocks with a light regex pass rather than eval'ing it.
  const groups: NavItem[] = []
  const groupBlocks = literal.match(/\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}/g) || []
  // Re-walk top-level objects only (depth-1 blocks) via manual bracket scan for accuracy.
  const topLevel: string[] = []
  {
    let d = 0, s = -1
    for (let j = 0; j < literal.length; j++) {
      if (literal[j] === '{') { if (d === 0) s = j; d++ }
      else if (literal[j] === '}') { d--; if (d === 0 && s >= 0) { topLevel.push(literal.slice(s, j + 1)); s = -1 } }
    }
  }
  const field = (block: string, name: string) => {
    const m = new RegExp(`${name}:\\s*'([^']*)'`).exec(block)
    return m ? m[1] : undefined
  }
  for (const block of topLevel) {
    // Strip the children sub-array before reading the group's own fields -- otherwise
    // a parent with no href/pageKey of its own (e.g. "Purchases") picks up its first
    // child's href by substring match, which is wrong.
    const childrenMatch = /children:\s*\[([\s\S]*)\]/.exec(block)
    const ownBlock = childrenMatch ? block.slice(0, childrenMatch.index) : block
    const label = field(ownBlock, 'label')
    if (!label) continue
    const item: NavItem = {
      label,
      href: field(ownBlock, 'href'),
      pageKey: field(ownBlock, 'pageKey'),
      ownerOnly: /ownerOnly:\s*true/.test(ownBlock),
    }
    if (childrenMatch) {
      const childBlocks: string[] = []
      let d = 0, s = -1
      const cs = childrenMatch[1]
      for (let j = 0; j < cs.length; j++) {
        if (cs[j] === '{') { if (d === 0) s = j; d++ }
        else if (cs[j] === '}') { d--; if (d === 0 && s >= 0) { childBlocks.push(cs.slice(s, j + 1)); s = -1 } }
      }
      // A group-level ownerOnly hides every child regardless of the child's own flag
      // (sidebar.tsx's canSee() filters groups first, then children) -- propagate it
      // so the matrix reflects what's actually reachable, not just the literal field.
      item.children = childBlocks.map((cb) => ({
        label: field(cb, 'label') || '',
        href: field(cb, 'href'),
        pageKey: field(cb, 'pageKey'),
        ownerOnly: item.ownerOnly || /ownerOnly:\s*true/.test(cb),
      }))
    }
    groups.push(item)
  }

  let out = HEADER('Navigation Map')
  out += `Parsed from \`apps/erp/components/sidebar.tsx\`. "Owner only" hides the item from the sidebar for non-owners as UX convenience -- the underlying route always enforces the same restriction server-side too.\n\n`
  out += `| Label | Route | Page key | Owner only? |\n|---|---|---|---|\n`
  for (const g of groups) {
    if (g.href) {
      out += `| ${g.label} | \`${g.href}\` | ${g.pageKey ?? ''} | ${g.ownerOnly ? 'yes' : ''} |\n`
    }
    for (const c of g.children ?? []) {
      out += `| ${g.label} > ${c.label} | \`${c.href}\` | ${c.pageKey ?? ''} | ${c.ownerOnly ? 'yes' : ''} |\n`
    }
  }
  write('nav-map.md', out)
  return groups
}

// ---------------------------------------------------------------------------
// 3b) generated-nav.json -- flat, advisor-consumable copy of the nav map.
// Written into apps/erp/lib/advisor/ (not docs/bible/generated/) so it's a
// plain JSON import Next.js bundles natively -- the advisor's locate resolver
// never does a runtime fs read, per the performance contract (one indexed
// round trip, nothing extra on the hot path).
// ---------------------------------------------------------------------------
function genNavJson(groups: NavItem[]) {
  const flat: { label: string; route: string; pageKey?: string; ownerOnly?: boolean }[] = []
  for (const g of groups) {
    if (g.href) flat.push({ label: g.label, route: g.href, pageKey: g.pageKey, ownerOnly: g.ownerOnly })
    for (const c of g.children ?? []) {
      if (c.href) flat.push({ label: `${g.label} > ${c.label}`, route: c.href, pageKey: c.pageKey, ownerOnly: c.ownerOnly })
    }
  }
  const outDir = resolve(ROOT, 'apps/erp/lib/advisor')
  mkdirSync(outDir, { recursive: true })
  writeFileSync(resolve(outDir, 'generated-nav.json'), JSON.stringify(flat, null, 2) + '\n', 'utf8')
  console.log('  wrote apps/erp/lib/advisor/generated-nav.json')
}

// ---------------------------------------------------------------------------
// 4) permissions.md -- role x page matrix, from nav map + profile_page_actions + redaction_rules
// ---------------------------------------------------------------------------
async function genPermissions(navGroups: NavItem[]) {
  const flat: { label: string; pageKey?: string; ownerOnly?: boolean }[] = []
  for (const g of navGroups) {
    if (g.href) flat.push({ label: g.label, pageKey: g.pageKey, ownerOnly: g.ownerOnly })
    for (const c of g.children ?? []) flat.push({ label: `${g.label} > ${c.label}`, pageKey: c.pageKey, ownerOnly: c.ownerOnly })
  }

  const { data: editGrants } = await supabaseAdmin
    .from('profile_page_actions')
    .select('page_key, can_edit, profiles(role)')
  const editableByRole = new Map<string, Set<string>>()
  for (const row of (editGrants || []) as any[]) {
    const role = row.profiles?.role
    if (!role || !row.can_edit) continue
    if (!editableByRole.has(row.page_key)) editableByRole.set(row.page_key, new Set())
    editableByRole.get(row.page_key)!.add(role)
  }

  const { data: redaction } = await supabaseAdmin
    .from('redaction_rules')
    .select('shape, field_name, hidden_from_employee, hidden_from_manager')

  let out = HEADER('Permissions Matrix')
  out += `Owner always has full view + edit access everywhere; this table covers manager/employee.\n\n`
  out += `## Page access (view)\n\n`
  out += `| Page | Manager | Employee |\n|---|---|---|\n`
  for (const item of flat) {
    if (item.ownerOnly) {
      out += `| ${item.label} | owner-only | owner-only |\n`
    } else if (item.pageKey) {
      out += `| ${item.label} | if granted \`${item.pageKey}\` | if granted \`${item.pageKey}\` |\n`
    } else {
      out += `| ${item.label} | visible to all signed-in staff | visible to all signed-in staff |\n`
    }
  }

  out += `\n## Edit grants currently configured (\`profile_page_actions\`)\n\n`
  out += `| Page key | Roles with edit access |\n|---|---|\n`
  for (const [key, roles] of [...editableByRole.entries()].sort()) {
    out += `| ${key} | ${[...roles].join(', ')} |\n`
  }

  out += `\n## Redacted fields (\`redaction_rules\`)\n\n`
  out += `| Shape | Field | Hidden from manager | Hidden from employee |\n|---|---|---|---|\n`
  for (const r of (redaction || []) as any[]) {
    out += `| ${r.shape} | ${r.field_name} | ${r.hidden_from_manager ? 'yes' : ''} | ${r.hidden_from_employee ? 'yes' : ''} |\n`
  }
  write('permissions.md', out)
}

// ---------------------------------------------------------------------------
// 5) categories.md -- sku_category_templates.field_schema per category
// ---------------------------------------------------------------------------
async function genCategories() {
  const { data, error } = await supabaseAdmin
    .from('sku_category_templates')
    .select('category, display_name, field_schema')
    .order('category')
  if (error) throw new Error(`sku_category_templates: ${error.message}`)

  let out = HEADER('SKU Category Templates')
  out += `Defines the spec schema captured per \`sku_master.category\`. Source of truth for what fields a SKU form shows.\n\n`
  for (const row of data || []) {
    out += `## ${row.category}${row.display_name ? ` — ${row.display_name}` : ''}\n\n`
    const schema = row.field_schema
    if (Array.isArray(schema)) {
      out += `| Field | Type | Options |\n|---|---|---|\n`
      for (const f of schema as any[]) {
        const opts = Array.isArray(f.options) ? f.options.join(', ') : (f.optionsCategory ?? '')
        out += `| ${f.name ?? f.key ?? ''} | ${f.type ?? ''} | ${opts} |\n`
      }
    } else if (schema && typeof schema === 'object') {
      out += '```json\n' + JSON.stringify(schema, null, 2) + '\n```\n'
    }
    out += '\n'
  }
  write('categories.md', out)
}

// ---------------------------------------------------------------------------
// 6) dropdowns.md -- custom_options grouped by category
// ---------------------------------------------------------------------------
async function genDropdowns() {
  const { data, error } = await supabaseAdmin
    .from('custom_options')
    .select('category, value')
    .order('category')
    .order('value')
  if (error) throw new Error(`custom_options: ${error.message}`)

  const byCat = new Map<string, string[]>()
  for (const row of data || []) {
    if (!byCat.has(row.category)) byCat.set(row.category, [])
    byCat.get(row.category)!.push(row.value)
  }

  let out = HEADER('Dropdown Options')
  out += `Owner-curated lists from \`custom_options\` (Settings -> Dropdown Options). ${byCat.size} categories, ${data?.length ?? 0} values total.\n\n`
  for (const [cat, values] of [...byCat.entries()].sort()) {
    out += `## ${cat} (${values.length})\n\n`
    out += values.map((v) => `- ${v}`).join('\n') + '\n\n'
  }
  write('dropdowns.md', out)
}

// ---------------------------------------------------------------------------
// 7) rpcs.md -- Postgres functions + signatures
// ---------------------------------------------------------------------------
async function genRpcs() {
  const { data, error } = await supabaseAdmin.rpc('bible_introspect_rpcs')
  if (error) throw new Error(`bible_introspect_rpcs: ${error.message}`)
  type Row = { function_name: string; arguments: string; return_type: string; function_comment: string | null }
  const rows = ((data || []) as Row[]).sort((a, b) => a.function_name.localeCompare(b.function_name))

  let out = HEADER('Database Functions (RPCs)')
  out += `${rows.length} functions in the \`public\` schema. Numbering, GST calc, reporting, and the reserve/reconcile flows all go through these -- application code must never re-implement one client-side.\n\n`
  out += `| Function | Arguments | Returns | Comment |\n|---|---|---|---|\n`
  for (const r of rows) {
    out += `| \`${r.function_name}\` | ${r.arguments || '—'} | ${r.return_type} | ${r.function_comment ?? ''} |\n`
  }
  write('rpcs.md', out)
}

// ---------------------------------------------------------------------------
// 8) status-values.md -- every CHECK constraint (asset status, PO status, etc.)
// ---------------------------------------------------------------------------
async function genStatusValues() {
  const { data, error } = await supabaseAdmin.rpc('bible_introspect_status_values')
  if (error) throw new Error(`bible_introspect_status_values: ${error.message}`)
  type Row = { table_name: string; column_name: string; constraint_name: string; check_clause: string }
  const rows = (data || []) as Row[]

  let out = HEADER('Status / Enum Values (CHECK constraints)')
  out += `Every CHECK constraint in \`public\` -- this is where asset status, PO status, payment status, and every other fixed-value domain is actually enforced.\n\n`
  out += `| Table | Column | Constraint | Definition |\n|---|---|---|---|\n`
  for (const r of rows.sort((a, b) => a.table_name.localeCompare(b.table_name))) {
    out += `| ${r.table_name} | ${r.column_name} | ${r.constraint_name} | \`${r.check_clause.replace(/\|/g, '\\|')}\` |\n`
  }
  write('status-values.md', out)
}

async function main() {
  console.log('Generating docs/bible/generated/**...')
  await genSchema()
  genApiRoutes()
  const navGroups = genNavMap()
  genNavJson(navGroups)
  await genPermissions(navGroups)
  await genCategories()
  await genDropdowns()
  await genRpcs()
  await genStatusValues()
  console.log('Done.')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
